# Generated by Django 5.1.7 on 2025-03-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobMatrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_resume',
            field=models.FileField(blank=True, db_column='applicant_resume', max_length=255, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_image',
            field=models.FileField(blank=True, db_column='company_image', max_length=255, null=True, upload_to='company_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_photo',
            field=models.FileField(blank=True, db_column='user_profile_photo', max_length=255, null=True, upload_to='profile_photos/'),
        ),
    ]
