# Generated by Django 5.1.7 on 2025-03-24 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("JobMatrix", "0002_alter_applicant_applicant_resume_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkExperience",
        ),
    ]
