# Generated by Django 5.1.7 on 2025-03-30 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("JobMatrix", "0003_delete_workexperience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="applicant_id",
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
