# Generated by Django 5.1.7 on 2025-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobMatrix', '0004_remove_skill_applicant_id_delete_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(db_column='job_title', max_length=255),
        ),
    ]
