# Generated by Django 5.1.7 on 2025-04-18 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_education_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='applicant_id',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='applicant_id',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
